---
- name: Kontrollera uppgraderingar och skicka till Discord
  hosts: all
  gather_facts: false
  vars:
    discord_webhook_url: "https://discord.com/api/webhooks/WEBHOOK-ID/WEBHOOK-TOKEN"

  tasks:

    - name: Hämta tillgängliga uppgraderingar
      ansible.builtin.command: apt list --upgradable
      register: upgrade_output
      changed_when: false

    - name: Extrahera lista på uppgraderbara paket
      set_fact:
        upgradable_packages: >-
          {{
            upgrade_output.stdout_lines
            | select("match", "^[^Listing].*upgradable from")
            | list
          }}

    - name: Formatera listan för Discord
      set_fact:
        discord_message: >-
          {%- if upgradable_packages | length > 0 -%}
          Följande paket kan uppgraderas på {{ inventory_hostname }}:
          {{ '\n' + upgradable_packages | join('\n') }}
          {%- else -%}
          Inga uppgraderingar tillgängliga på {{ inventory_hostname }}.
          {%- endif -%}

    - name: Skicka meddelande till Discord
      ansible.builtin.uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        headers:
          Content-Type: application/json
        body_format: json
        body:
          content: "{{ discord_message }}"
      delegate_to: localhost
