---
- name: Check and report available updates
  hosts: all
  gather_facts: false

  vars:
    discord_webhook_url: "https://discord.com/api/webhooks/DITT_WEBHOOK_ID/DITT_TOKEN"
    discord_username: "UpdateBot"
    discord_avatar_url: "https://i.imgur.com/4M34hi2.png"

  tasks:
    - name: Get list of upgradable packages
      shell: apt list --upgradable 2>/dev/null | tail -n +2
      register: apt_upgrades
      changed_when: false

    - name: Filter list of upgradable packages
      set_fact:
        upgradable_packages: "{{ apt_upgrades.stdout_lines | reject('match', '^Listing...') | list }}"

    - name: Format update list
      set_fact:
        updates_formatted: "{{ upgradable_packages | join('\n') }}"

    - name: Send update report to Discord
      uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        headers:
          Content-Type: application/json
        body_format: json
        body: >-
          {{
            {
              "username": discord_username,
              "avatar_url": discord_avatar_url,
              "content": "**{{ inventory_hostname }}**\n"
                         + (updates_formatted | default('Inga uppdateringar tillgängliga.') | regex_replace('\\\\n', '\n'))
            }
          }}
        status_code: 204
      when: upgradable_packages | length > 0
