---
- name: Check available updates and report
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    discord_webhook_url: "{{ lookup('env', 'DISCORD_WEBHOOK_URL') }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Gather package facts
      package_facts:
        manager: auto

    - name: Filter list of upgradable packages
      set_fact:
        upgradable_packages: "{{ ansible_facts.packages | dict2items
          | selectattr('value', 'select', 'updated')
          | map(attribute='key') | list }}"

    - name: Check if there are any available updates
      set_fact:
        updates_available: "{{ upgradable_packages | length > 0 }}"

    - name: Print available updates to Ansible console
      when: updates_available
      debug:
        msg: |
          Available updates on {{ inventory_hostname }}:
          {{ upgradable_packages | join('\n') }}

    - name: Send Discord notification about available updates
      when: updates_available
      uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: >
          {{
            {
              "content": "**" + inventory_hostname + "**\nThe following updates are available:\n" + (upgradable_packages | join('\n'))
            } | to_json
          }}
        body_format: json
        status_code: 204
