---
- name: Check available updates and report to console and Discord
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    discord_webhook_url: "{{ lookup('env', 'DISCORD_WEBHOOK_URL') }}"

  tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Get list of upgradable packages (suppress warnings)
      shell: apt list --upgradable 2>/dev/null | tail -n +2
      register: apt_upgradable
      changed_when: false
      failed_when: false

    - name: Filter list of upgradable packages
      set_fact:
        upgradable_packages: "{{ apt_upgradable.stdout_lines | reject('search', '\\[installed\\]$') | list }}"

    - name: Check if there are any available updates
      set_fact:
        updates_available: "{{ upgradable_packages | length > 0 }}"

    - name: Print available updates to Ansible console
      when: updates_available
      debug:
        msg: |
          Available updates on {{ inventory_hostname }}:
          {{ upgradable_packages | join('\n') }}

    - name: Format Discord message
      when: updates_available
      set_fact:
        discord_message: |
          **{{ inventory_hostname }}**
          The following updates are available:
          ```
          {{ upgradable_packages | join('\n') }}
          ```

    - name: Send message to Discord
      when: updates_available
      uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "content": "{{ discord_message | replace('\n', '\\n') }}"
          }
        body_format: json
        status_code: 204
