---
- name: Check disk space
  hosts: "all"

  tasks:
    - name: Check disk space available
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          df -Ph / | awk 'NR==2 {print $5}' | sed 's/%//'
        executable: /bin/bash
      changed_when: false
      check_mode: false
      register: disk_usage

    - name: Disk usage is above 80%
      ansible.builtin.fail:
        msg: "Disk usage is at {{ disk_usage.stdout }}%, which is above 80%! Immediate action required."
      when: disk_usage.stdout | int > 80

    - name: Print disk usage
      ansible.builtin.debug:
        msg: "Disk usage is at {{ disk_usage.stdout }}%"
      changed_when: false
