---
- name: Lägg till Docker repo, installera Docker och skapa användare
  hosts: all
  become: true
  tasks:

    - name: Installera beroenden
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Skapa keyrings-katalog
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Hämta Dockers GPG-nyckel
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Hämta Ubuntu codename
      command: lsb_release -cs
      register: ubuntu_codename
      changed_when: false

    - name: Lägg till Docker APT-repo
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable

    - name: Uppdatera APT-cache
      apt:
        update_cache: yes

    - name: Installera Docker och tillägg
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Starta och aktivera Docker-tjänsten
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Skapa användare dockeradmin
      user:
        name: dockeradmin
        shell: /bin/bash
        groups: docker
        append: yes
        create_home: yes

    - name: Visa info om skapad användare
      debug:
        msg: "Användaren 'dockeradmin' är skapad och tillagd i gruppen 'docker'."
