---
- name: Check if reboot is required and display affected packages
  hosts: all
  become: yes
  tasks:
    - name: Check if reboot is required (Ubuntu/Debian)
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      when: ansible_facts['os_family'] == "Debian"

    - name: Get list of packages requiring reboot (Ubuntu/Debian)
      shell: cat /var/run/reboot-required.pkgs
      when: reboot_required.stat.exists
      register: pkgs_contents
      changed_when: false

    - name: Check if reboot is required (RHEL-based)
      command: needs-restarting -r
      register: reboot_required_rhel
      ignore_errors: true
      changed_when: false
      when: ansible_facts['os_family'] == "RedHat"

    - name: Show package contents (Ubuntu/Debian)
      debug:
        var: pkgs_contents.stdout_lines
      when: reboot_required.stat.exists

    - name: Show packages needing restart (RHEL-based)
      debug:
        var: reboot_required_rhel.stdout_lines
      when: ansible_facts['os_family'] == "RedHat" and reboot_required_rhel.rc != 0

    - name: Reboot the server if needed (Ubuntu/Debian)
      reboot:
      when: reboot_required.stat.exists

    - name: Reboot the server if needed (RHEL-based)
      reboot:
      when: ansible_facts['os_family'] == "RedHat" and reboot_required_rhel.rc != 0
