---
- name: Install updates and notify if updates installed
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    discord_webhook_url: "{{ lookup('env', 'DISCORD_WEBHOOK_URL') }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install available upgrades
      apt:
        upgrade: dist
        update_cache: yes
      register: upgrade_result
      changed_when: upgrade_result.stdout != "" or upgrade_result.stderr != ""

    - name: Get list of installed packages today
      command: >
        bash -c "grep ' install ' /var/log/dpkg.log | grep \"$(date '+%Y-%m-%d')\""
      register: installed_packages
      changed_when: false
      failed_when: false

    - name: Check if updates were installed
      set_fact:
        updates_installed: "{{ installed_packages.stdout != '' }}"

    - name: Print installed updates to Ansible console
      when: updates_installed
      debug:
        msg: |
          Updates installed on {{ inventory_hostname }}:
          {{ installed_packages.stdout }}

    - name: Send Discord notification if updates were installed
      when: updates_installed
      block:
        - name: Prepare message
          set_fact:
            discord_message: |
              **{{ inventory_hostname }}**
              The following updates were installed today:
              {{ installed_packages.stdout }}
